# Dummy makefile

all: generate test

fmt:
	@echo 'Run goimports'
	find . -name "*.go" -exec goimports -w {} \;

dep:
	echo 'TODO: install dependencies'

generate:
	echo 'TODO: generate mocks'

test:
	echo 'TODO: run tests'
